name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-and-test:
    name: Linting & testing
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Installing dependencies
        run: bun install --frozen-lockfile
      - name: Running audit
        run: bun audit --audit-level critical
      - name: Checking formatting
        run: bun run format:check
      - name: Linting code
        run: bun run lint
      - name: Type checking
        run: bun run typecheck
      - name: Running tests
        run: bun run test
