name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-and-test:
    name: Linting & testing
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Configuring NodeJS environment
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          cache: npm
      - name: Installing dependencies
        run: npm ci
      - name: Running audit
        run: npm audit --audit-level critical
      - name: Checking formatting
        run: npm run format:check
      - name: Linting code
        run: npm run lint
      - name: Running tests
        run: npm test
